version: '3'

services:

  php:
    build: './docker/php'
    volumes:
      - '.:/var/www/html'
    ports:
      - '9000:9000' 

  worker:
    build: './docker/php'
    volumes:
      - '.:/var/www/html'
    entrypoint: ["php", "artisan", "queue:listen"]
    restart: unless-stopped

  mysql:
    image: 'mysql'
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql/volume:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'

  nginx:
    image: 'nginx:stable-alpine'
    ports:
      -  '80:80'
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'

  redis:
    image: redis
    command: redis-server
    volumes:
      - ./docker/redis:/data
    ports:
      - 6379:6379

  echo-server:
    build: './docker/echo-server'
    volumes:
      - ./docker/echo-server:/work
    ports:
      - "6001:6001"
    command: laravel-echo-server start


